### ISSUE TITLE
Missing cars

### ISSUE THREAD

**Issue by FilipeOS** [KilowattApp/open-ev-data#11]
Hi,

Can this cars be added? And maybe others?

- BMW i5
- Cupra Formentor

**Comment by FilipeOS** [comment]
- Tesla M3 SR Plus de 2020

**Comment by FilipeOS** [comment]
- Hyundai Ioniq 6

**Comment by tijs** [comment]
@FilipeOS if you have the chance it would be much appreciated if you can add these models, you can base your updated details on existing data from manufacturers, the web etc. I'm working on making adding data easier but for now you'd have to update the JSON file and then validate it's ok with the new tests.

**Comment by FilipeOS** [comment]
That new way is only for that brands? Or you are doing a generic curve? Because I do that too. Can you shared the percentage and values?

**Comment by tijs** [comment]
no you can add for any existing brand or model with the CLI. And yes If you do not know the curve the script will guesstimate a generic curve for you based on the Max DC charge value.
