### ISSUE TITLE
Add the 2024 Mini Cooper SE

### ISSUE THREAD

**Issue by stoplis** [KilowattApp/open-ev-data#17]
Please add the 2024 Mini Cooper SE. Included in the links is the charge curve for charging details.

**Comment by stoplis** [comment]
Vehicle Details:

Brand: Mini
Model: Cooper Electric SE (2024)
Type: car
Battery Capacity: 49.2 kWh
AC Charging Power: 11 kW
DC Charging Power: 95 kW
Consumption: 13 kWh/100km
Sources:
https://www.mini.co.uk/en_GB/home/range/all-electric-mini-cooper/technical-data.html
https://ev-database.org/uk/car/1998/Mini-Cooper-Electric-SE
https://evkx.net/models/mini/cooper/cooper_se/chargingcurve/

**Comment by tijs** [comment]
Coming in the upcoming update 👍🏻
