### ISSUE TITLE
Vehicle Suggestion: Mini Aceman SE

### ISSUE THREAD

**Issue by stoplis** [KilowattApp/open-ev-data#18]
Vehicle Details:
- Brand: Mini
- Model: Aceman SE
- Type: car
- Battery Capacity: 49.2 kWh
- AC Charging Power: 11 kW
- DC Charging Power: 95 kW
- Consumption: 17 kWh/100km

Sources:
https://www.mini.co.uk/en_GB/home/range/all-electric-mini-aceman/technical-data.html
https://ev-database.org/uk/car/2191/Mini-Aceman-SE#efficiency
https://evkx.net/models/mini/cooper/cooper_se/chargingcurve/

This car has the same battery and charging hardware as the 2024 Mini SE

**Comment by tijs** [comment]
Coming in the upcoming update 👍🏻
