### ISSUE TITLE
Vehicle Suggestion: Mini Countryman SE ALL4

### ISSUE THREAD

**Issue by stoplis** [KilowattApp/open-ev-data#19]
Vehicle Details:
- Brand: Mini
- Model: Countryman SE ALL4
- Type: car
- Battery Capacity: 64.6 kWh
- AC Charging Power: 11 kW
- DC Charging Power: 128 kW
- Consumption: 15.5 kWh/100km

Sources:
https://www.mini.co.uk/en_GB/home/range/all-electric-mini-countryman/technical-data.html
https://ev-database.org/uk/car/1995/Mini-Countryman-SE-ALL4
https://evkx.net/models/mini/countryman/countryman_se_all4/chargingcurve/

**Comment by tijs** [comment]
Coming in the upcoming update 👍🏻
